export const rentalConfig = {
  packages: [
    {
      id: 'package-1',
      name: 'Single Camera Package',
      description: 'Perfect for simple events and presentations',
      price: 1500,
      image: '/images/package-1.jpg',
      keyFeatures: [
        'Single 4K Camera',
        'Professional Audio',
        'Basic Lighting',
        'Live Streaming',
      ],
      includedItems: [],
      slug: 'single-camera',
    },
    {
      id: 'package-2',
      name: 'Two Camera Package',
      description: 'Ideal for medium-sized events',
      price: 2500,
      image: '/images/package-2.jpg',
      keyFeatures: [
        'Two 4K Cameras',
        'Professional Audio',
        'Enhanced Lighting',
        'Live Streaming',
        'Switching & Graphics',
      ],
      includedItems: [],
      slug: 'two-camera',
    },
    {
      id: 'package-3',
      name: 'Three Camera Package',
      description: 'Complete coverage for larger events',
      price: 3500,
      image: '/images/package-3.jpg',
      keyFeatures: [
        'Three 4K Cameras',
        'Professional Audio',
        'Full Lighting Kit',
        'Live Streaming',
        'Advanced Graphics',
        'Recording & Editing',
      ],
      includedItems: [],
      slug: 'three-camera',
    },
  ],
  addOns: [
    {
      id: 'addon-camera',
      name: '+1 Camera Angle',
      description: 'Add another 4K camera angle',
      price: 800,
      image: '/images/addon-camera.jpg',
      type: 'addon',
      value: 'recording-streaming',
    },
    {
      id: 'addon-streaming',
      name: 'Additional Streaming',
      description: 'Stream to additional platforms',
      price: 300,
      image: '/images/addon-streaming.jpg',
      type: 'addon',
      value: 'recording-streaming',
    },
    {
      id: 'addon-graphics',
      name: 'Graphics Package',
      description: 'Custom graphics and lower thirds',
      price: 500,
      image: '/images/addon-graphics.jpg',
      type: 'addon',
      value: 'production-enhancements',
    },
  ],
  keyFeatures: [],
  addonGroups: [
    {
      id: 'recording-streaming',
      name: 'Recording & Streaming',
    },
    {
      id: 'production-enhancements',
      name: 'Production Enhancements',
    },
  ],
} 